version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - sqlnetwork

volumes:
  sqlserverdata:

networks:
  sqlnetwork:

#   docker-compose up -d
#   docker-compose down --remove-orphans
